title: Alejandro Gatica (@gatikman)
description: Software developer with a strong blend of entrepreneurship, systems architecture, and algorithmic trading.
logo: assets/photo.png
show_downloads: false
google_analytics: G-2ZYEFWTEWZ
theme: jekyll-theme-minimal